language: android

before_install:
 - chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository

notifications:
  email: false

sudo: false

script: ./gradlew build